//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDE_Operations_In_ASP.NET.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRUDE_Operations_In_ASP.NET.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 249, 65, 68;243, 114, 44;248, 150, 30;249, 132, 74;249, 199, 79;144, 190, 109;67, 170, 139;67, 170, 139;87, 117, 144;87, 117, 144;
        ///247, 37, 133;181, 23, 158;114, 9, 183;86, 11, 173;72, 12, 168;58, 12, 163;63, 55, 201;67, 97, 238;72, 149, 239;76, 201, 240;
        ///0, 18, 25;0, 95, 115;10, 147, 150;148, 210, 189;233, 216, 166;238, 155, 0;202, 103, 2;187, 62, 3;174, 32, 18;155, 34, 38;
        ///3, 7, 30;55, 6, 23;106, 4, 15;157, 2, 8;208, 0, 0;220, 47, 2;232, 93, 4;244, 140, 6;250, 163, 7;255, 186, 8;
        ///1, 42, 74;1, 58, 99;1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afghanistan
        ///Åland Islands
        ///Albania
        ///Algeria
        ///American Samoa
        ///Andorra
        ///Angola
        ///Anguilla
        ///Antarctica
        ///Antigua and Barbuda
        ///Argentina
        ///Armenia
        ///Aruba
        ///Australia
        ///Austria
        ///Azerbaijan
        ///Bahamas
        ///Bahrain
        ///Bangladesh
        ///Barbados
        ///Belarus
        ///Belgium
        ///Belize
        ///Benin
        ///Bermuda
        ///Bhutan
        ///Bolivia (Plurinational State of)
        ///Bonaire, Sint Eustatius and Saba
        ///Bosnia and Herzegovina
        ///Botswana
        ///Bouvet Island
        ///Brazil
        ///British Indian Ocean Territory
        ///Brunei Darussalam
        ///Bulgaria
        ///Burkina Faso
        ///Burundi
        ///Cabo Verde
        ///Cambodia
        ///Cameroon
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
    }
}
